// 加载环境变量
require('dotenv').config();

module.exports = {
  apps: [
    // 验证者节点 1
    {
      name: 'ju-chain-validator1',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator1',
        '--config', './config-validator1.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR1_HTTP_PORT || '8545'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR1_WS_PORT || '8546'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR1_ENGINE_PORT || '8551'),
        '--port=' + (process.env.VALIDATOR1_P2P_PORT || '30301'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR1_ADDRESS || '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        '--password', './private-chain/data-validator1/password.txt',
        '--unlock', process.env.VALIDATOR1_ADDRESS || '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator1-error.log',
      out_file: './ju-logs/validator1-out.log',
      log_file: './ju-logs/validator1-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 验证者节点 2
    {
      name: 'ju-chain-validator2',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator2',
        '--config', './config-validator2.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR2_HTTP_PORT || '8553'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR2_WS_PORT || '8554'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR2_ENGINE_PORT || '8555'),
        '--port=' + (process.env.VALIDATOR2_P2P_PORT || '30303'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR2_ADDRESS || '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
        '--password', './private-chain/data-validator2/password.txt',
        '--unlock', process.env.VALIDATOR2_ADDRESS || '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator2-error.log',
      out_file: './ju-logs/validator2-out.log',
      log_file: './ju-logs/validator2-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 验证者节点 3
    {
      name: 'ju-chain-validator3',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator3',
        '--config', './config-validator3.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR3_HTTP_PORT || '8556'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR3_WS_PORT || '8557'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR3_ENGINE_PORT || '8558'),
        '--port=' + (process.env.VALIDATOR3_P2P_PORT || '30304'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR3_ADDRESS || '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
        '--password', './private-chain/data-validator3/password.txt',
        '--unlock', process.env.VALIDATOR3_ADDRESS || '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator3-error.log',
      out_file: './ju-logs/validator3-out.log',
      log_file: './ju-logs/validator3-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 验证者节点 4
    {
      name: 'ju-chain-validator4',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator4',
        '--config', './config-validator4.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR4_HTTP_PORT || '8559'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR4_WS_PORT || '8560'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR4_ENGINE_PORT || '8561'),
        '--port=' + (process.env.VALIDATOR4_P2P_PORT || '30305'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR4_ADDRESS || '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
        '--password', './private-chain/data-validator4/password.txt',
        '--unlock', process.env.VALIDATOR4_ADDRESS || '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator4-error.log',
      out_file: './ju-logs/validator4-out.log',
      log_file: './ju-logs/validator4-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 验证者节点 5
    {
      name: 'ju-chain-validator5',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator5',
        '--config', './config-validator5.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR5_HTTP_PORT || '8562'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR5_WS_PORT || '8563'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR5_ENGINE_PORT || '8564'),
        '--port=' + (process.env.VALIDATOR5_P2P_PORT || '30306'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR5_ADDRESS || '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
        '--password', './private-chain/data-validator5/password.txt',
        '--unlock', process.env.VALIDATOR5_ADDRESS || '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator5-error.log',
      out_file: './ju-logs/validator5-out.log',
      log_file: './ju-logs/validator5-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 候选验证者节点 6
    {
      name: 'ju-chain-candidate-validator6',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator6',
        '--config', './config-validator6.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR6_HTTP_PORT || '8565'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR6_WS_PORT || '8566'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR6_ENGINE_PORT || '8567'),
        '--port=' + (process.env.VALIDATOR6_P2P_PORT || '30307'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR6_ADDRESS || '0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc',
        '--password', './private-chain/data-validator6/password.txt',
        '--unlock', process.env.VALIDATOR6_ADDRESS || '0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator6-error.log',
      out_file: './ju-logs/validator6-out.log',
      log_file: './ju-logs/validator6-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    // 候选验证者节点 7
    {
      name: 'ju-chain-candidate-validator7',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-validator7',
        '--config', './config-validator7.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.VALIDATOR7_HTTP_PORT || '8568'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,miner,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.VALIDATOR7_WS_PORT || '8569'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,miner,congress',
        '--authrpc.port=' + (process.env.VALIDATOR7_ENGINE_PORT || '8570'),
        '--port=' + (process.env.VALIDATOR7_P2P_PORT || '30308'),
        '--mine',
        '--miner.etherbase', process.env.VALIDATOR7_ADDRESS || '0x50c554ac9c134491818fa6f21d504f2ae5bd9c26',
        '--password', './private-chain/data-validator7/password.txt',
        '--unlock', process.env.VALIDATOR7_ADDRESS || '0x50c554ac9c134491818fa6f21d504f2ae5bd9c26',
        '--allow-insecure-unlock'
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.VALIDATOR_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/validator7-error.log',
      out_file: './ju-logs/validator7-out.log',
      log_file: './ju-logs/validator7-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'ju-chain-syncnode',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.NETWORK_ID || '202599',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-sync',
        '--config', './config-syncnode.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.SYNCNODE_HTTP_PORT || '8547'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.SYNCNODE_WS_PORT || '8548'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,congress',
        '--authrpc.port=' + (process.env.SYNCNODE_ENGINE_PORT || '8552'),
        '--port=' + (process.env.SYNCNODE_P2P_PORT || '30302')
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.SYNCNODE_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/syncnode-error.log',
      out_file: './ju-logs/syncnode-out.log',
      log_file: './ju-logs/syncnode-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'ju-chain-syncnode-mainnet',
      script: './build/bin/geth',
      args: [
        '--networkid', process.env.MAINNET_NETWORK_ID || '210000',
        '--txpool.nolocals',
        '--txpool.globalslots', process.env.TXPOOL_GLOBAL_SLOTS || '12800',
        '--txpool.globalqueue', process.env.TXPOOL_GLOBAL_QUEUE || '5120',
        '--txpool.lifetime', process.env.TXPOOL_LIFETIME || '10m0s',
        '--txpool.pricelimit', process.env.TXPOOL_PRICE_LIMIT || '1000000000',
        '--datadir', './private-chain/data-sync-mainnet',
        '--config', './config-syncnode-mainnet.toml',
        '--syncmode=full',
        '--gcmode=archive',
        '--verbosity=' + (process.env.VERBOSITY || '3'),
        '--http',
        '--http.port=' + (process.env.SYNCNODE_MAINNET_HTTP_PORT || '8549'),
        '--http.corsdomain=*',
        '--http.vhosts=*',
        '--http.addr=0.0.0.0',
        '--http.api=web3,debug,eth,txpool,net,personal,admin,congress',
        '--ws',
        '--ws.addr=0.0.0.0',
        '--ws.port=' + (process.env.SYNCNODE_MAINNET_WS_PORT || '8550'),
        '--ws.origins=*',
        '--ws.api=debug,eth,txpool,net,engine,personal,admin,congress',
        '--authrpc.port=' + (process.env.SYNCNODE_MAINNET_ENGINE_PORT || '8571'),
        '--port=' + (process.env.SYNCNODE_MAINNET_P2P_PORT || '30312')
      ],
      cwd: process.cwd(),
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: process.env.SYNCNODE_MAINNET_MEMORY_LIMIT || '2G',
      env: {
        NODE_ENV: 'production'
      },
      error_file: './ju-logs/syncnode-mainnet-error.log',
      out_file: './ju-logs/syncnode-mainnet-out.log',
      log_file: './ju-logs/syncnode-mainnet-combined.log',
      time: true,
      merge_logs: true,
      kill_timeout: 30000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s'
    }
  ],

  deploy: {
    production: {
      user: 'enty',
      host: 'localhost',
      ref: 'origin/v1.13.15-poa-security-fixes',
      repo: 'git@github.com:your-repo/ju-chain.git',
      path: process.cwd(),
      'pre-deploy-local': '',
      'post-deploy': 'make geth && pm2 reload ecosystem.config.js --env production',
      'pre-setup': ''
    }
  }
};
